# Generated by Django 2.1.7 on 2019-05-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtTheVet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaratie',
            name='declaratie_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='factuur',
            name='factuur_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
